export const homeCategory = [
	{ "key": "key-0", "name": "推荐", "category": "main" },
	{ "key": "key-2", "name": "热点", "category": "news_hot" },
	{ "key": "key-4", "name": "图片", "category": "news_image" }, 
	{ "key": "key-5", "name": "科技", "category": "news_tech" }, 
	{ "key": "key-6", "name": "娱乐", "category": "news_entertainment" }, 
	{ "key": "key-7", "name": "游戏", "category": "news_game" }, 
	{ "key": "key-8", "name": "体育", "category": "news_sports" }, 
	{ "key": "key-10", "name": "财经", "category": "news_finance" }, 
	{ "key": "key-11", "name": "数码", "category": "digital" }, 
	{ "key": "key-13", "name": "军事", "category": "news_military" }, 
	{ "key": "key-14", "name": "国际", "category": "news_world" }, 
	{ "key": "key-15", "name": "时尚", "category": "news_fashion" }, 
	{ "key": "key-16", "name": "旅游", "category": "news_travel" }, 
	{ "key": "key-17", "name": "探索", "category": "news_discovery" }, 
	{ "key": "key-18", "name": "育儿", "category": "news_baby" }, 
	{ "key": "key-19", "name": "养生", "category": "news_regimen" }, 
	{ "key": "key-20", "name": "美文", "category": "news_essay" }, 
	{ "key": "key-21", "name": "历史", "category": "news_history" }, 
	{ "key": "key-22", "name": "美食", "category": "news_food" }
]
